[project]
name = 'blaze-limit'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.blaze-v1]
path = 'contracts/blaze-v1.clar'
clarity_version = 3
epoch = 3.1

[contracts.pepe-token-subnet-v1]
path = 'contracts/pepe-token-subnet-v1.clar'
clarity_version = 3
epoch = 3.1

[contracts.sbtc-token-subnet-v1]
path = 'contracts/sbtc-token-subnet-v1.clar'
clarity_version = 3
epoch = 3.1

[contracts.shark-faktory-pool]
path = 'contracts/shark-faktory-pool.clar'
clarity_version = 3
epoch = 3.1

[contracts.styx-v1]
path = 'contracts/styx-v1.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
